---
- name: Установка и настройка PostgreSQL
  hosts: ec2_servers
  become: yes
  vars:
    db_name: oscar_db
    db_user: oscar
    db_password: your_password_here  # Замените на ваш пароль
  tasks:
    - name: Обновить кеш пакетов APT
      apt:
        update_cache: yes

    - name: Установка СУБД PostgreSQL и дополнительных пакетов
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql
        - postgresql-contrib

    - name: Убедиться, что PostgreSQL запущен и включен
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Создать базу данных
      become_user: postgres
      shell: >
        psql -c "CREATE DATABASE {{ db_name }};"

    - name: Создать пользователя
      become_user: postgres
      shell: >
        psql -c "CREATE USER {{ db_user }} WITH PASSWORD '{{ db_password }}';"

    - name: Дать пользователю все привилегии на базе данных
      become_user: postgres
      shell: >
        psql -c "GRANT ALL PRIVILEGES ON DATABASE {{ db_name }} TO {{ db_user }};"
