---
- name: Установить и настроить NGINX и скопировать HTML страницу
  hosts: cometa_1
  become: yes
  tasks:
    - name: Установить NGINX
      apt:
        name: nginx
        state: present

    - name: Убедиться, что директория /var/www/html существует
      file:
        path: /var/www/html
        state: directory

    - name: Копировать HTML файл в /var/www/html
      copy:
        src: /home/vboxdamir/test.html
        dest: /var/www/html/test.html

