name: Push-to-EC2-Prod

# Запускать по расписанию
on:
  schedule:
    - cron: '50 14 * * *'

jobs:
  deploy:
    name: Deploy to EC2 on schedule
    runs-on: ubuntu-latest
    steps:
      # Проверить файлы
      - name: Checkout the files
        uses: actions/checkout@v2
      
      # Подключиться к серверу, используя заданные ранее переменные, и
      # загрузить в папку $TARGET наш репозиторий
      - name: Deploy to Cometa-Prod
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}

      # Выполнить удаленные команды на сервере - переместить файлы,
      # перезапустить веб-сервер
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mv /home/ubuntu/sum_html1/* /var/www/sum_html.page/
            sudo service nginx restart

