name: Deploy Application

on:
  push:
    branches:
      - main  # Замените на вашу ветку, если нужно

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my_web_app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push my_web_app

      - name: Deploy using Ansible
        uses: appleboy/ansible-action@v1
        with:
          playbook: playbook.yml
          inventory: ${{ secrets.ANSIBLE_INVENTORY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

